# Borders

default_border pixel 2
default_floating_border pixel 2

# Gaps

gaps inner 4
gaps outer 1
smart_gaps off

# ============================================================================

# Twilight Theme Colors

# ============================================================================

client.focused          #C1C88D #C1C88D #000000 #C1C88D #C1C88D
client.unfocused        #454545 #000000 #A09998 #000000 #454545
client.focused_inactive #555555 #000000 #D6D2C8 #000000 #555555
client.urgent           #C34143 #C34143 #000000 #C34143 #C34143

# ============================================================================

# Twilight Colors

# ============================================================================

set $bg         #000000
set $bg-alt     #303030

set $accent     #C1C88D
set $accent2    #DEBF7C

set $white      #FFFEDB
set $gray       #A09998
set $gray-dark  #1D2021
