# Twilight — i3lock palette

inside_color=1D1D1DEE
ring_color=FFFEDBFF
line_color=00000000
separator_color=00000000

insidever_color=303030EE
insidewrong_color=454545EE

ringver_color=C1C88DFF
ringwrong_color=C34143FF

keyhl_color=DEBF7CFF
bshl_color=AA9AACFF

time_color=FFFEDBFF
date_color=D6D2C8FF
layout_color=A09998FF

verif_color=C1C88DFF
wrong_color=C34143FF
