# =========================
# Twilight Theme
# =========================

# Background / Foreground

background #000000
foreground #FFFEDB

# =========================
# Normal Colors
# =========================

color0  #303030
color1  #C34143
color2  #A2A970
color3  #DEBF7C
color4  #8B9698
color5  #AA9AAC
color6  #C1C88D
color7  #D6D2C8

# =========================
# Bright Colors
# =========================

color8  #555555
color9  #C34143
color10 #C1C88D
color11 #E3D896
color12 #8B9698
color13 #AA9AAC
color14 #A2A970
color15 #FFFEDB

# =========================
# Cursor
# =========================

cursor #FFFEDB
cursor_text_color #000000

# =========================
# Selection
# =========================

selection_background #C1C88D
selection_foreground #000000

# =========================
# Borders
# =========================

active_border_color   #C1C88D
inactive_border_color #454545
bell_border_color     #C34143
