[window.padding]
x = 0
y = 0

[colors.primary]
background = "#000000"
foreground = "#ffffff"   # brighter default text

[colors.normal]
black   = "#1a1a1a"
red     = "#ff4d4d"
green   = "#c0c0c0"
yellow  = "#ff6666"
blue    = "#a0a0a0"
magenta = "#ff7575"
cyan    = "#d0d0d0"
white   = "#ffffff"

[colors.bright]
black   = "#555555"
red     = "#ff8080"
green   = "#ffffff"
yellow  = "#ff9999"
blue    = "#d9d9d9"
magenta = "#ffb3b3"
cyan    = "#ffffff"
white   = "#ffffff"

#JetBrains font and SizeControl
[font]
size = 10.25

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

#UnderLine Cursor
[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.25

[window]
opacity = 0.6
