[window.padding]
x = 0
y = 0

[colors.primary]
background = "#050505"
foreground = "#e8e8e8"

[colors.normal]
black   = "#1a1a1a"
red     = "#707070"
green   = "#c0c0c0"
yellow  = "#a0a0a0"
blue    = "#b0b0b0"
magenta = "#d0d0d0"
cyan    = "#e0e0e0"
white   = "#ffffff"

[colors.bright]
black   = "#555555"
red     = "#909090"
green   = "#ffffff"
yellow  = "#d9d9d9"
blue    = "#e8e8e8"
magenta = "#f0f0f0"
cyan    = "#ffffff"
white   = "#ffffff"

#JetBrains font and SizeControl
[font]
size = 10.75

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

#UnderLine Cursor
[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.25

[window]
opacity = 0.63
