# Autostart

exec --no-startup-id dex --autostart --environment i3

exec_always --no-startup-id picom --backend glx --config ~/.config/picom/picom.conf

exec_always --no-startup-id autotiling

exec_always --no-startup-id ~/.config/polybar/launch.sh

exec_always --no-startup-id feh --bg-fill ~/Pictures/100.jpeg

exec_always --no-startup-id killall dunst; dunst

exec_always --no-startup-id setxkbmap -option caps:escape

exec_always --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec --no-startup-id xsetroot -cursor_name left_ptr

exec --no-startup-id sh -c "sleep 0.75 && ~/.config/i3/scripts/lock.sh"

exec_always --no-startup-id xrdb -merge ~/.Xresources

exec_always xinput set-prop 16 "libinput Tapping Enabled" 1

exec_always --no-startup-id xinput set-prop 16 "libinput Natural Scrolling Enabled" 1

exec --no-startup-id ~/.config/i3/scripts/idle-lock.sh
