# Scratchpad

bindsym --release $mod+Shift+minus move scratchpad
bindsym --release $mod+minus scratchpad show

for_window [title="scratchpad"] floating enable, resize set 800 500, move position center
for_window [title="scratchpad"] move scratchpad

# Floating

bindsym --release $mod+shift+space floating toggle,resize set 800 500,move position center

bindsym --release $mod+space focus mode_toggle

for_window [floating] resize set 70 ppt 50 ppt move position center

# Focus

bindsym --release $mod+a focus parent
bindsym --release $mod+c focus child
