# Focus Windows
bindsym --release $mod+h focus left
bindsym --release $mod+j focus down
bindsym --release $mod+k focus up
bindsym --release $mod+l focus right

# Move Windows
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
