# Split
bindsym --release $mod+b split h
bindsym --release $mod+v split v

# Fullscreen
bindsym --release $mod+f fullscreen toggle

# Layout
bindsym --release $mod+s layout stacking
bindsym --release $mod+w layout tabbed
bindsym --release $mod+e layout toggle split

# Kill Window
bindsym --release $mod+Shift+q kill
