# -----------------------------
# Volume
# -----------------------------
bindsym F2 exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym F3 exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym F4 exec pactl set-sink-mute @DEFAULT_SINK@ toggle

# -----------------------------
# Brightness
# -----------------------------
bindsym Mod1+F2 exec brightnessctl set 5%-
bindsym Mod1+F3 exec brightnessctl set +5%

# -----------------------------
# Redshift
# -----------------------------
bindsym $mod+Shift+Up exec "redshift -O 5500"
bindsym $mod+Shift+Down exec "redshift -x"
bindsym $mod+Shift+t exec --no-startup-id ~/.local/bin/theme-menu
# -----------------------------
# MPD
# -----------------------------
bindsym --release F8 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh toggle
bindsym --release F5 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh prev
bindsym --release F6 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh next
bindsym --release Shift+F9 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh stop
bindsym --release F9 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh update
bindsym --release Mod1+Shift+f exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh fav
bindsym --release Mod1+Shift+d exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh trash
bindsym --release F7 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh cycle
bindsym --release Shift+F7 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh cycle_prev
bindsym --release Shift+F6 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh forward
bindsym --release Shift+F5 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh backward
bindsym --release Shift+F8 exec --no-startup-id /home/harsh/.config/i3/scripts/mpd.sh repeat_one

# -----------------------------
# Opacity
# -----------------------------
bindsym Mod1+o exec --no-startup-id ~/.config/i3/scripts/opacity.sh up
bindsym Mod1+Shift+o exec --no-startup-id ~/.config/i3/scripts/opacity.sh down
bindsym $mod+Shift+o exec --no-startup-id ~/.config/i3/scripts/opacity.sh reset
