# -----------------------------
# Terminal
# -----------------------------
bindsym --release Mod1+t exec kitty
bindsym --release Mod1+Return exec alacritty

# -----------------------------
# App Launcher
# -----------------------------
bindsym --release $mod+d exec rofi -show drun

# -----------------------------
# Applications
# -----------------------------
bindsym --release Mod1+b exec helium-browser
bindsym --release Mod1+z exec obsidian
bindsym --release Mod1+Shift+g exec gtk-launch tekken3
bindsym --release Mod1+Shift+b exec helium-browser --incognito

bindsym --release Mod1+e exec kitty -e yazi

bindsym --release Mod1+Shift+l exec --no-startup-id kitty -e env NVIM_APPNAME=nvim2 nvim +"Leet"
bindsym --release Mod1+n exec --no-startup-id kitty -e env NVIM_APPNAME=nvim2 nvim

bindsym --release Mod1+r exec localsend
bindsym --release Mod1+4 exec alacritty -e toofan
bindsym --release Mod1+d exec alacritty -e discordo
Bindsym --release Mod1+q exec kitty -e btop

bindsym --release Mod1+Shift+v exec code
bindsym --release Mod1+8 exec antigravity
bindsym --release Mod1+9 exec cursor
bindsym --release Mod1+v exec kitty -e vim ~/Notes/todo
