# -----------------------------
# PWAs
# -----------------------------
bindsym --release Mod1+1 exec helium-browser --app="https://monkeytype.com"
bindsym --release Mod1+2 exec helium-browser --app="https://keybr.com"
bindsym --release Mod1+3 exec helium-browser --app="https://www.typingclub.com"

bindsym --release Mod1+c exec helium-browser --app="https://chatgpt.com"

bindsym --release Mod1+Shift+c exec helium-browser --app="https://lichess.org/"

bindsym --release Mod1+a exec helium-browser --app="https://hianime.lol/home"

bindsym --release Mod1+Shift+n exec helium-browser --app="https://net11.cc"

bindsym --release Mod1+y exec helium-browser --app="https://youtube.com"

bindsym --release Mod1+x exec chromium --app="https://leetcode.com/problemset"

bindsym --release Mod1+g exec helium-browser --app="https://github.com"
