# -----------------------------
# Polybar
# -----------------------------
bindsym --release Mod1+Shift+p exec --no-startup-id ~/.config/i3/scripts/polybar_toggle.sh
bindsym $mod+Shift+p exec --no-startup-id ~/.config/polybar/toggle_position.sh

# -----------------------------
# Wallpaper
# -----------------------------
bindsym Mod1+Shift+w exec ~/.config/i3/scripts/wall_toggle.sh

# -----------------------------
# Screenshot
# -----------------------------
bindsym Mod1+s exec --no-startup-id flameshot gui -p ~/Screenshots -c
bindsym $mod+Shift+s exec --no-startup-id ~/.config/i3/scripts/ss_window.sh

# -----------------------------
# Screen Recording
# -----------------------------
bindsym Mod1+Shift+r exec --no-startup-id ~/.config/i3/scripts/record_toggle.sh

# -----------------------------
# Bluetooth
# -----------------------------
bindsym --release $mod+Shift+b exec --no-startup-id ~/.config/i3/scripts/bt-toggle.sh

# -----------------------------
# Touchpad
# -----------------------------
bindsym --release F12 exec ~/.config/i3/scripts/touchpad-toggle.sh

# -----------------------------
# Auto Mute
# -----------------------------
bindsym --release $mod+Shift+m exec ~/.config/i3/scripts/auto_mute.sh

# -----------------------------
# Emoji Picker
# -----------------------------
bindsym Mod1+Shift+e exec --no-startup-id rofi -show emoji

# -----------------------------
# Lock
# -----------------------------
bindsym $mod+Shift+x exec --no-startup-id ~/.config/i3/scripts/lock1.sh

# -----------------------------
# Power
# -----------------------------
bindsym --release Mod1+F4 exec poweroff
