# -----------------------------
# Gap Toggle
# -----------------------------
bindsym --release Mod1+Shift+q exec --no-startup-id ~/.config/i3/scripts/gap.sh

# -----------------------------
# Typing Mode
# -----------------------------
bindsym --release Mod1+5 exec --no-startup-id ~/.config/i3/scripts/typing-mode.sh

# -----------------------------
# Kill Mode
# -----------------------------
bindsym --release Mod1+Shift+m exec --no-startup-id ~/.config/i3/scripts/kill-mode.sh

# -----------------------------
# WhatsApp
# -----------------------------
bindsym --release Mod1+w exec ~/.config/i3/scripts/whatsapp.sh

# -----------------------------
# Apple Music
# -----------------------------
bindsym --release Mod1+Shift+a exec ~/.config/i3/scripts/applemusic.sh

# -----------------------------
# Music Mode
# -----------------------------
bindsym F1 exec ~/.config/i3/scripts/music-mode.sh
