# -----------------------------
# Scratchpad
# -----------------------------
for_window [title="scratchpad"] floating enable, resize set 800 500, move position center
for_window [title="scratchpad"] move scratchpad

# -----------------------------
# Floating Windows
# -----------------------------
for_window [floating] resize set 70 ppt 50 ppt move position center

for_window [class="python3"] floating enable

# -----------------------------
# Window Rules
# -----------------------------
for_window [class="Brave-browser" instance="music.youtube.com"] move container to workspace "music"

for_window [class="Brave-browser" instance="web.whatsapp.com"] move container to workspace "whatsapp"
