# -----------------------------
# Reload
# -----------------------------
bindsym --release $mod+Shift+c reload

# -----------------------------
# Restart
# -----------------------------
bindsym --release $mod+Shift+r restart
