# =========================
# PaperColor Theme
# =========================

[urgency_low]
timeout = 4
background = "#F2EDE3"
foreground = "#5C5954"
frame_color = "#B8B1A6"

[urgency_normal]
timeout = 6
background = "#F2EDE3"
foreground = "#292724"
frame_color = "#9A761F"

[urgency_critical]
timeout = 0
background = "#F2EDE3"
foreground = "#292724"
frame_color = "#A33A3A"
