# =========================
# PaperColor Theme
# =========================

# Background / Foreground
background #F2EDE3
foreground #292724

# =========================
# Normal Colors
# =========================

color0  #292724
color1  #A33A3A
color2  #4F6B4A
color3  #9A761F
color4  #4A6280
color5  #7A596F
color6  #4F7470
color7  #B8B1A6

# =========================
# Bright Colors
# =========================

color8  #5C5954
color9  #C05252
color10 #668A60
color11 #B4933A
color12 #617D9F
color13 #966F89
color14 #64918B
color15 #292724

# =========================
# Cursor
# =========================

cursor #292724
cursor_text_color #F2EDE3

# =========================
# Selection
# =========================

selection_background #D8D0C2
selection_foreground #292724

# =========================
# Borders
# =========================

active_border_color   #4A6280
inactive_border_color #B8B1A6
bell_border_color     #A33A3A
