# =========================
# Gruvbox Theme
# =========================

[urgency_low]
timeout = 4
background = "#282828"
foreground = "#928374"
frame_color = "#504945"

[urgency_normal]
timeout = 6
background = "#282828"
foreground = "#ebdbb2"
frame_color = "#d79921"

[urgency_critical]
timeout = 0
background = "#282828"
foreground = "#fb4934"
frame_color = "#cc241d"
