# Borders

default_border pixel 2
default_floating_border pixel 2

# Gaps

gaps inner 4
gaps outer 1
smart_gaps off

# Theme Colors

client.focused          #d79921 #d79921 #282828 #d79921 #d79921
client.unfocused        #504945 #282828 #928374 #282828 #504945
client.focused_inactive #665c54 #282828 #d5c4a1 #282828 #665c54
client.urgent           #cc241d #cc241d #282828 #cc241d #cc241d

# Gruvbox Colors

set $bg         #000000
set $bg-alt     #3c3836

set $accent     #d79921
set $accent2    #d65d0e

set $white      #ebdbb2
set $gray       #928374
set $gray-dark  #1d2021
