# Gruvbox — i3lock palette

inside_color=1D2021EE
ring_color=EBDBB2FF
line_color=00000000
separator_color=00000000

insidever_color=282828EE
insidewrong_color=3C3836EE

ringver_color=B8BB26FF
ringwrong_color=FB4934FF

keyhl_color=FABD2FFF
bshl_color=FE8019FF

time_color=FBF1C7FF
date_color=D5C4A1FF
layout_color=A89984FF

verif_color=B8BB26FF
wrong_color=FB4934FF
