# Borders

default_border pixel 2
default_floating_border pixel 2

# Gaps

gaps inner 4
gaps outer 1
smart_gaps off

# ==================================================
# Theme Colors
# ==================================================

client.focused          #CBA6F7 #CBA6F7 #1E1E2E #CBA6F7 #CBA6F7
client.unfocused        #45475A #1E1E2E #6C7086 #1E1E2E #45475A
client.focused_inactive #585B70 #1E1E2E #BAC2DE #1E1E2E #585B70
client.urgent            #F38BA8 #F38BA8 #1E1E2E #F38BA8 #F38BA8

# ==================================================
# Catppuccin Colors
# ==================================================

set $bg         #1E1E2E
set $bg-alt     #313244

set $accent     #CBA6F7
set $accent2    #FAB387

set $white      #CDD6F4
set $gray       #6C7086
set $gray-dark  #181825
