#!/bin/bash

PICOM="$HOME/.config/picom"
STATE="$HOME/.cache/picom-mode"

mkdir -p "$HOME/.cache"

current_mode="normal"

[[ -f "$STATE" ]] && current_mode=$(cat "$STATE")

case "$current_mode" in

normal)
    echo "blur" >"$STATE"
    pkill picom
    sleep 0.2
    picom --config "$PICOM/picom-blur.conf" &
    notify-send "Picom" "Blur mode enabled"
    ;;

blur)
    echo "animation" >"$STATE"
    pkill picom
    sleep 0.2
    picom --config "$PICOM/picom-animation.conf" &
    notify-send "Picom" "Animation mode enabled"
    ;;

animation)
    rm -f "$STATE"
    pkill picom
    sleep 0.2
    picom --config "$PICOM/picom.conf" &
    notify-send "Picom" "Normal mode enabled"
    ;;

*)
    rm -f "$STATE"
    pkill picom
    sleep 0.2
    picom --config "$PICOM/picom.conf" &
    notify-send "Picom" "Normal mode enabled"
    ;;
esac
