configuration {
    modi: "drun";

    case-sensitive: false;
    cycle: true;

    matching: "normal";
    tokenize: true;
    normalize-match: true;

    show-icons: true;
    icon-theme: "Tela-dark";

    disable-history: false;
    sorting-method: "normal";
    max-history-size: 25;

    drun-categories: "";
    drun-match-fields: "name,generic,exec,categories,keywords";

    drun-display-format: "{name} [<span weight='light' size='small'><i>({generic})</i></span>]";

    drun-show-actions: false;

    terminal: "rofi-sensible-terminal";

    click-to-exit: true;
    steal-focus: false;

    timeout {
        action: "kb-cancel";
        delay: 0;
    }
}
