# =========================
# Berserk Theme
# =========================

[urgency_low]
timeout = 4
background = "#000000"
foreground = "#a0a0a0"
frame_color = "#3a3a3a"

[urgency_normal]
timeout = 6
background = "#000000"
foreground = "#ffffff"
frame_color = "#d0d0d0"

[urgency_critical]
timeout = 0
background = "#000000"
foreground = "#ffffff"
frame_color = "#ffffff"
