# Borders
default_border pixel 2
default_floating_border pixel 2

# Gaps
gaps inner 4
gaps outer 1
smart_gaps off

# Theme Colors
client.focused          #ffffff #ffffff #000000 #ffffff #ffffff
client.unfocused        #505050 #101010 #707070 #101010 #505050
client.focused_inactive #808080 #101010 #c0c0c0 #101010 #808080
client.urgent           #ffffff #ffffff #000000 #ffffff #ffffff

# Berserk Colors
set $bg         #050505
set $bg-alt     #101010

set $accent     #ffffff
set $accent2    #c0c0c0

set $white      #ffffff
set $gray       #707070
set $gray-dark  #2a2a2a
