; ==================================================
;                  Base Bar
; ==================================================

[bar/main]
width = 100%

background = ${colors.bar-background}
foreground = ${colors.text}

line-size = 0
border-size = 0
border-color = ${colors.transparent}

padding-left = 0
padding-right = 1

module-margin = 0

separator = " "
separator-foreground = ${colors.transparent}

font-0 = "jetbrainsmono nerd font:size=10;2"
font-1 = "jetbrainsmono nerd font:size=12;2"
font-2 = "PolyCat:size=15;3"

modules-left = rofi i3 polycat
modules-center = date
modules-right = recording mpd pulseaudio brightness memory cpu temperature battery wlan

cursor-click = pointer
enable-ipc = true
wm-restack = i3
override-redirect = false

; ==================================================
;                    Top Bar
; ==================================================

[bar/top]
inherit = bar/main
bottom = false
height = 12pt

; ==================================================
;                  Bottom Bar
; ==================================================

[bar/bottom]
inherit = bar/main
bottom = true
height = 14pt
