## Configuration file for CAVA.
##
## Lines starting with ; show config parameters and default values.
## Remove the ; to change parameters.

[general]

# Auto reload config if the configuration file has changed.
# 1 = on, 0 = off.
live-config = 0

# Framerate.
framerate = 60

# Automatically adjust sensitivity.
# 0 = off, 1 = normal, 2..n = more aggressive.
autosens = 1

# Manual sensitivity in %.
sensitivity = 100

# Scaling can be 'linear' or 'decibel'.
scaling = linear

# Number of bars.
# 0 = automatically fill the console.
bars = 0

# Bar width and space between bars.
bar_width = 2
bar_spacing = 1

# Center bars in terminal if there is space.
center_align = 1

# Maximum height of bars in percent of terminal height.
max_height = 100

# Frequency range.
lower_cutoff_freq = 50
higher_cutoff_freq = 10000

# Seconds with no input before cava goes to sleep.
# 0 = disabled.
sleep_timer = 0


[input]

# PipeWire audio input.
method = pipewire
source = auto

# Default PipeWire settings.
sample_rate = 48000
sample_bits = 16

# PipeWire options.
active = 1
remix = 1
virtual = 1


[output]

# Default output method.
method = noncurses

# Orientation.
orientation = bottom

# Visual channels.
channels = stereo
mono_option = average
reverse = 0

# Split stereo.
split_stereo = 0
left_bottom = 1

# X-axis labels.
xaxis = none

# Synchronized sync.
synchronized_sync = 0

# Disable console blanking.
disable_blanking = 0

# Show flat bar at bottom when idle.
show_idle_bar_heads = 1

# Show waveform instead of frequency spectrum.
waveform = 0


[color]

# Sakura Night — Wallpaper Palette

background = '#000000'
foreground = '#FDF1B2'

gradient = 1
gradient_count = 6

# Bottom -> top

gradient_color_1 = '#731C46'   # Dark Sakura / Wine
gradient_color_2 = '#BD4667'   # Crimson Pink
gradient_color_3 = '#EA4865'   # Bright Coral
gradient_color_4 = '#F99C8F'   # Peach
gradient_color_5 = '#27859A'   # Teal
gradient_color_6 = '#4D6F82'   # Muted Blue

[smoothing]

# Default smoothing behavior.
monstercat = 0
waves = 0

# Default noise reduction.
noise_reduction = 77


[eq]

# Equalizer disabled by default.


