# =========================================================
# Sakura Night — i3lock palette
# =========================================================

# Main lock screen
inside_color=171521EE
ring_color=F06A86FF
line_color=00000000
separator_color=00000000

# Verification / wrong password
insidever_color=302038EE
insidewrong_color=321C29EE

ringver_color=E78FA4FF
ringwrong_color=C94768FF

# Key interaction
keyhl_color=FFB7C5FF
bshl_color=6E5262FF

# Text
time_color=FFF0D0FF
date_color=E8DCE1FF
layout_color=BFAAB5FF

# Status text
verif_color=E78FA4FF
wrong_color=F05A7AFF
