# =========================
# Sakura Night Theme
# =========================

# Background / Foreground

background #000000
foreground #FDF1B2

# =========================
# Normal Colors
# =========================

color0  #000000
color1  #BD4667
color2  #27859A
color3  #DEBF7C
color4  #4D6F82
color5  #731C47
color6  #F99C8F
color7  #D6D2C8

# =========================
# Bright Colors
# =========================

color8  #4D6F82
color9  #EA4865
color10 #39A6B8
color11 #FDF1B2
color12 #6B8FA3
color13 #A94B70
color14 #FFB0A3
color15 #FDF1B2

# =========================
# Cursor
# =========================

cursor #FDF1B2
cursor_text_color #0D1A2E

# =========================
# Selection
# =========================

selection_background #EA4865
selection_foreground #0D1A2E

# =========================
# Borders
# =========================

active_border_color   #EA4865
inactive_border_color #555555
bell_border_color     #BD4667
