# Borders

default_border pixel 2
default_floating_border pixel 2

# Gaps

gaps inner 4
gaps outer 1
smart_gaps off

# ==================================================
# Nord Theme Colors
# ==================================================

client.focused          #88C0D0 #88C0D0 #2E3440 #88C0D0 #88C0D0
client.unfocused        #4C566A #2E3440 #616E88 #2E3440 #4C566A
client.focused_inactive #434C5E #2E3440 #D8DEE9 #2E3440 #434C5E
client.urgent           #BF616A #BF616A #2E3440 #BF616A #BF616A

# ==================================================
# Nord Colors
# ==================================================

set $bg         #2E3440
set $bg-alt     #3B4252

set $accent     #88C0D0
set $accent2    #81A1C1

set $white      #D8DEE9
set $gray       #616E88
set $gray-dark  #242933
