# =========================
# Everforest Theme
# =========================

[urgency_low]
timeout = 4
background = "#2D353B"
foreground = "#859289"
frame_color = "#4A555B"

[urgency_normal]
timeout = 6
background = "#2D353B"
foreground = "#D3C6AA"
frame_color = "#A7C080"

[urgency_critical]
timeout = 0
background = "#2D353B"
foreground = "#F2D5A0"
frame_color = "#E67E80"
