# Borders

default_border pixel 2
default_floating_border pixel 2

# Gaps

gaps inner 4
gaps outer 1
smart_gaps off

# ==================================================
# Everforest Theme Colors
# ==================================================

client.focused          #A7C080 #A7C080 #2D353B #A7C080 #A7C080
client.unfocused        #4A555B #2D353B #859289 #2D353B #4A555B
client.focused_inactive #475258 #2D353B #D3C6AA #2D353B #475258
client.urgent           #E67E80 #E67E80 #2D353B #E67E80 #E67E80

# ==================================================
# Everforest Colors
# ==================================================

set $bg         #2D353B
set $bg-alt     #3A454A

set $accent     #A7C080
set $accent2    #E69875

set $white      #D3C6AA
set $gray       #859289
set $gray-dark  #232A2E
