conky.config = {
    update_interval = 1,

    own_window = true,
    own_window_type = 'override',
    own_window_class = 'Conky',

    own_window_argb_visual = true,
    own_window_argb_value = 140,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    double_buffer = true,
    use_xft = true,

    draw_borders = false,
    draw_outline = false,
    draw_shades = false,

    minimum_width = 540,
    minimum_height = 220,

    alignment = 'top_left',
    gap_x = 40,
    gap_y = 55,

    default_color = 'FFFFFF',

    font = 'JetBrainsMono Nerd Font:size=16',

    border_inner_margin = 20,
    border_outer_margin = 0,

    lua_draw_hook_pre = 'draw_clock_box',

    out_to_x = true,
};

conky.text = [[

${voffset 28}${font JetBrainsMono Nerd Font:size=14}${color BFBFBF}CLOCK

${voffset 12}${font JetBrainsMono Nerd Font:size=70:bold}${color FFFFFF}${time %H:%M}

${voffset -62}${offset 310}${font JetBrainsMono Nerd Font:size=20}${time %A}

${offset 310}${font JetBrainsMono Nerd Font:size=17}${color C8C8C8}${time %d %B %Y}

${voffset 35}${font JetBrainsMono Nerd Font:size=13}${color 8F8F8F}"Struggle. Endure. Contend."
]];
