conky.config = {
    update_interval = 1,

    own_window = true,
    own_window_type = 'override',
    own_window_class = 'Conky',

    own_window_argb_visual = true,
    own_window_argb_value = 140,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    double_buffer = true,

    use_xft = true,

    draw_borders = false,
    draw_outline = false,
    draw_shades = false,

    minimum_width = 390,
    minimum_height = 330,

    alignment = 'top_left',

    gap_x = 55,
    gap_y = 430,

    default_color = 'FFFFFF',

    font = 'JetBrainsMono Nerd Font:size=14',

    lua_load = '~/.config/conky/bars.lua',
    lua_draw_hook_pre = 'draw_music_box',

    out_to_x = true,
}

conky.text = [[

${voffset 26}${font JetBrainsMono Nerd Font:size=14}${color BFBFBF}MUSIC

${voffset 25}

${font JetBrainsMono Nerd Font:size=22}♫

${offset 45}${voffset -22}${font JetBrainsMono Nerd Font:size=16}${color FFFFFF}Berserk OST

${offset 45}${font JetBrainsMono Nerd Font:size=13}${color AAAAAA}Susumu Hirasawa

${voffset 28}${color 666666}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${color FFFFFF}1:25${alignr}4:27

${voffset 25}${alignc}${font JetBrainsMono Nerd Font:size=22}⏮   ⏯   ⏭

]]
